[package]
name = "gasless_sol"
version = "0.1.0"
description = "Anchor program for gasless-like escrow transfers"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "gasless_sol"
[dependencies]
anchor-lang = { version = "0.28.0", features = ["init-if-needed"] }
anchor-spl  = { version = "0.28.0", features = ["token-2022"] }
spl-token-2022 = "1.0.0"


[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
