[package]
name = "gasless_sol"
version = "0.1.0"
description = "Anchor program for gasless-like escrow transfers"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "gasless_sol"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.28.0", features = ["init-if-needed"] }
anchor-spl = "0.28.0"
